routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Backend\AdminProfileController as BackendAdminProfileController;
use App\Http\Controllers\Backend\AdminUserController;
use App\Http\Controllers\Backend\BrandController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\CouponController;
use App\Http\Controllers\Backend\LanguageController;
use App\Http\Controllers\Backend\OrderController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\ReportController;
use App\Http\Controllers\Backend\ReturnController;
use App\Http\Controllers\Backend\ShippingAreaController;
use App\Http\Controllers\Backend\SiteSettingController;
use App\Http\Controllers\Backend\SliderController;
use App\Http\Controllers\Backend\SubCategoryController;
use App\Http\Controllers\Backend\SubSubCategoryController;
use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\IndexController;
use App\Http\Controllers\Frontend\SearchController;
use App\Http\Controllers\User\AllUserController;
use App\Http\Controllers\User\CartPageController;
use App\Http\Controllers\User\CashController;
use App\Http\Controllers\User\CheckoutController;
use App\Http\Controllers\User\StripeController;
use App\Http\Controllers\User\WishlistController;
use App\Models\User;
use Doctrine\DBAL\Schema\Index;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;



Route::group(['prefix' => 'admin', 'middleware' => ['admin:admin']], function () {

    Route::get('/login', [AdminController::class, 'loginForm']);

    Route::post('/login', [AdminController::class, 'store'])->name('admin.login');
});


//user routes

Route::middleware(['auth:sanctum,web', 'verified'])->get('/dashboard', function () {

    $id = Auth::user()->id;
    $user = User::find($id);

    return view('dashboard', compact('user'));
})->name('dashboard');

Route::get('/', [IndexController::class, 'index'])->name('index');

Route::get('/user.logout', [IndexController::class, 'userLogout'])->name('user.logout');

Route::get('/user.profile', [IndexController::class, 'userProfile'])->name('user.profile');

Route::post('/user.profile.store', [IndexController::class, 'userProfileStore'])
    ->name('user.profile.store');

Route::get('/user.change.password', [IndexController::class, 'userChangePassword'])
    ->name('change.password');

Route::post('/user.password.update', [IndexController::class, 'userUpdatePassword'])
    ->name('user.password.update');

Route::middleware(['auth:admin'])->group(function () {


    Route::middleware(['auth:sanctum,admin', 'verified'])->get('admin/dashboard', function () {
        return view('admin.index');
    })->name('dashboard')->middleware('auth:admin');

    //Admin routes
    Route::get('/logout', [AdminController::class, 'destroy'])->name('admin.logout');

    Route::get('/adminProfile', [BackendAdminProfileController::class, 'adminProfile'])->name('admin.profile');

    Route::get('/adminProfileEdit', [BackendAdminProfileController::class, 'adminProfileEdit'])
        ->name('admin.profile_edit');

    Route::post('/adminProfileStore', [BackendAdminProfileController::class, 'adminProfileStore'])
        ->name('admin.profile.store');

    Route::get('/adminChangePassword', [BackendAdminProfileController::class, 'adminChangePassword'])
        ->name('admin.change.password');

    Route::post('/updateChangePassword', [BackendAdminProfileController::class, 'updateChangePassword'])
        ->name('update.change.password');
}); // end admin middleware

//Brands all route

Route::prefix('brand')->group(function () {

    Route::get('/view', [BrandController::class, 'brandView'])->name('all.brands');

    Route::post('/store', [BrandController::class, 'brandStore'])->name('brand.store');

    Route::get('/edit/{id}', [BrandController::class, 'brandEdit'])->name('brand.edit');

    Route::post('/update/{id}', [BrandController::class, 'brandUpdate'])->name('brand.update');

    Route::get('/delete/{id}', [BrandController::class, 'brandDelete'])->name('brand.delete');
});

//Admin Category all route

Route::prefix('category')->group(function () {

    Route::get('/view', [CategoryController::class, 'categoryView'])->name('all.category');

    Route::post('/store', [CategoryController::class, 'categoryStore'])->name('category.store');

    Route::get('/edit/{id}', [CategoryController::class, 'categoryEdit'])->name('category.edit');

    Route::post('/update/{id}', [CategoryController::class, 'categoryUpdate'])->name('category.update');

    Route::get('/delete/{id}', [CategoryController::class, 'categoryDelete'])->name('category.delete');

    //Admin Sub Category all route

    Route::get('/sub/view', [SubCategoryController::class, 'index'])->name('all.subcategory');

    Route::post('/sub/store', [SubCategoryController::class, 'store'])->name('subcategory.store');

    Route::get('/sub/edit/{id}', [SubCategoryController::class, 'edit'])->name('subcategory.edit');

    Route::post('/sub/update/', [SubCategoryController::class, 'update'])->name('subcategory.update');

    Route::get('/sub/delete/{id}', [SubCategoryController::class, 'delete'])->name('subcategory.delete');

    //Admin Sub Category all route

    Route::get('/sub/sub/view', [SubSubCategoryController::class, 'index'])->name('all.subsubcategory');

    Route::get('/subcategory/ajax/{category_id}', [SubSubCategoryController::class, 'getSubCategory'])
        ->name('getSubCategory');

    Route::get('/sub-subcategory/ajax/{subcategory_id}', [SubSubCategoryController::class, 'GetSubSubCategory']);

    Route::post('/sub/sub/store', [SubSubCategoryController::class, 'store'])->name('subsubcategory.store');

    Route::get('/sub/sub/edit/{id}', [SubSubCategoryController::class, 'edit'])->name('subsubcategory.edit');

    Route::post('/sub/sub/update/', [SubSubCategoryController::class, 'update'])->name('subsubcategory.update');

    Route::get('/sub/sub/delete/{id}', [SubSubCategoryController::class, 'delete'])->name('subsubcategory.delete');
});

Route::prefix('product')->group(function () {

    Route::get('/add', [ProductController::class, 'create'])->name('add.product');

    Route::post('/store', [ProductController::class, 'store'])->name('product.store');

    Route::get('/manage', [ProductController::class, 'index'])->name('manage.product');

    Route::get('/show/{id}', [ProductController::class, 'show'])->name('product.view');

    Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('product.edit');

    Route::post('/update', [ProductController::class, 'update'])->name('product.update');

    Route::post('/multi/image', [ProductController::class, 'updateMultiImg'])->name('update.image');

    Route::post('/thambnail/image', [ProductController::class, 'updateThamImg'])->name('update.image');

    Route::get('/multiImg/delete/{id}', [ProductController::class, 'multiImgDel'])->name('product.multiImgDel');

    Route::get('/active/{id}', [ProductController::class, 'active'])->name('product.active');

    Route::get('/inactive/{id}', [ProductController::class, 'inactive'])->name('product.inactive');

    Route::get('/delete/{id}', [ProductController::class, 'delete'])->name('product.delete');
});

Route::prefix('slider')->group(function () {

    Route::get('/index', [SliderController::class, 'index'])->name('slider');

    Route::post('/store', [SliderController::class, 'store'])->name('slider.store');

    Route::get('/edit/{id}', [SliderController::class, 'sliderEdit'])->name('slider.edit');

    Route::post('/update', [SliderController::class, 'sliderUpdate'])->name('slider.update');

    Route::get('/delete/{id}', [SliderController::class, 'sliderDelete'])->name('slider.delete');

    Route::get('/active/{id}', [SliderController::class, 'slideractive'])->name('slider.active');

    Route::get('/inactive/{id}', [SliderController::class, 'sliderInactive'])->name('slider.inactive');
});



// multi language all route

Route::get('/language/english', [LanguageController::class, 'english'])->name('english.language');

Route::get('/language/hindi', [LanguageController::class, 'hindi'])->name('hindi.language');
// product detail page
Route::get('product/detail/{id}/{slug}', [IndexController::class, 'productDetail'])->name('product.detail');
// product tag
Route::get('product/tag/{tag}', [IndexController::class, 'productTag']);
//Subcategory-wise data
Route::get('subcategory/product/{subcat_id}/{slug}', [IndexController::class, 'subCatWiseProduct']);
//Subsubcategory-wise data
Route::get('subsubcategory/product/{subsubcat_id}/{slug}', [IndexController::class, 'subSububCatWiseProduct']);
//Product view model
Route::get('product/view/model/{id}', [IndexController::class, 'productViewAjax']);
//Add to cart
Route::post('/cart/data/store/{id}', [CartController::class, 'addToCart']);
//Add to mini cart
Route::get('/product/mini/cart/', [CartController::class, 'addMiniCart']);
//Remove to mini cart
Route::get('/minicart/product-remove/{rowId}', [CartController::class, 'removeMiniCart']);

Route::post('/add-to-wishlist/{product_id}', [CartController::class, 'addToWishList'])->name('addToWishList');

Route::group(
    //Add to wishlist
    ['prefix' => 'user', 'middleware' => ['user', 'auth'], 'namespace' => 'User'],
    function () {

        Route::get('/wishlist', [WishlistController::class, 'wishlist'])->name('wishlist');

        Route::get('/get-wishlist/product/', [WishlistController::class, 'getWishlist']);

        Route::get('/wishlist-remove/{id}', [WishlistController::class, 'removeWishlist']);

        Route::post('/stripe-order/', [StripeController::class, 'stripeOrder'])->name('stripe.order');

        Route::get('/my/order/', [AllUserController::class, 'myOrders'])->name('my.order');

        Route::get('/order_details/{order_id}', [AllUserController::class, 'detailOrders']);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Cache;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'phone',
        'password',
        'last_seen',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
    // Accessor
    public function getProfileImageAttribute()
    {
        $defaultPath = url('upload/no_image.jpg');

        $path = url('upload/user_images/' . $this->profile_photo_path);

        return $this->profile_photo_path == '' ? $defaultPath : $path;
    }

    //User Active Show
    public function UserOnline()
    {
     return Cache::has('user-is-online' . $this->id);
    }
}

resources/views/admin/admin_change_password.blade.php
@extends('admin.admin_master')
@section('admin')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<div class="container-full">

    <section class="content">

        <!-- Basic Forms -->
        <div class="box">
            <div class="box-header with-border">
                <h4 class="box-title">Admin Change Password</h4>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col">
                        <form action="{{ route('update.change.password') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-12">

                                    <div class="row">
                                        <div class="col-md-6">

                                            <div class="form-group">
                                                <h5>Current Password<span class="text-danger">*</span></h5>
                                                <div class="controls">
                                                    <input type="password" name="oldpassword" class="form-control"
                                                        required="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <h5>New Password<span class="text-danger">*</span></h5>
                                                <div class="controls">
                                                    <input type="password" name="password" class="form-control"
                                                        required="">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <h5>Confirm Password<span class="text-danger">*</span></h5>
                                                <div class="controls">
                                                    <input type="password" name="password_confirmation"
                                                        class="form-control" required="">
                                                </div>
                                            </div>

                                        </div>

                                    </div>

                                    <div class="text-xs-right">
                                        <button type="submit" class="btn btn-rounded btn-primary">Update</button>
                                    </div>
                        </form>

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

    </section>
</div>
<script type="text/javascript">
    $(document).ready(function(){
            $('#image').change(function(e){
                var reader = new FileReader();
                reader.onload = function(e){
                    $('#showImage').attr('src',e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            });
        });
</script>
@endsection

resources/views/admin/admin_master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../images/favicon.ico">

    <title>Easy E-commerce Admin - Dashboard</title>

    <!-- Vendors Style-->
    <link rel="stylesheet" href="{{ asset('backend/css/vendors_css.css') }}">

    <!-- Style-->
    <link rel="stylesheet" href="{{ asset('backend/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('backend/css/skin_color.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css">

</head>

<body class="hold-transition dark-skin sidebar-mini theme-primary fixed">

    <div class="wrapper">

        @include('admin.body.header')

        <!-- Left side column. contains the logo and sidebar -->
        @include('admin.body.sidebar')


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            @yield('admin')

        </div>
        <!-- /.content-wrapper -->
        @include('admin.body.footer')


        <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>

    </div>
    <!-- ./wrapper -->




    <!-- Vendor JS -->
    <script src="{{ asset('backend/js/vendors.min.js') }}"></script>
    <script src="{{ asset('../assets/icons/feather-icons/feather.min.js') }}"></script>
    <script src="{{ asset('../assets/vendor_components/easypiechart/dist/jquery.easypiechart.js') }}"></script>
    <script src="{{ asset('../assets/vendor_components/apexcharts-bundle/irregular-data-series.js') }}"></script>
    <script src="{{ asset('../assets/vendor_components/apexcharts-bundle/dist/apexcharts.js') }}"></script>
    @yield('scrpit')
    <!-- /// Tgas Input Script -->
    <script src="{{ asset('../assets/vendor_components/bootstrap-tagsinput/dist/bootstrap-tagsinput.js') }}"></script>

    <!-- // CK EDITOR  -->
    <script src="{{ asset('../assets/vendor_components/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('../assets/vendor_plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js') }}"></script>
    <script src="{{ asset('backend/js/pages/editor.js') }}"></script>



    <!-- Sunny Admin App -->
    <script src="{{ asset('backend/js/template.js') }}"></script>
    <script src="{{ asset('backend/js/pages/dashboard.js') }}"></script>


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        @if (Session::has('message'))
            var type = "{{ Session::get('alert-type', 'info') }}"
            switch(type){
            case 'info':
            toastr.info(" {{ Session::get('message') }} ");
            break;

            case 'success':
            toastr.success(" {{ Session::get('message') }} ");
            break;

            case 'warning':
            toastr.warning(" {{ Session::get('message') }} ");
            break;

            case 'error':
            toastr.error(" {{ Session::get('message') }} ");
            break;
            }
        @endif
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <script src="{{ asset('backend/js/code.js') }}"></script>


</body>

</html>

resources/views/admin/admin_profile_edit.blade.php
@extends('admin.admin_master')
@section('admin')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<div class="container-full">

    <section class="content">

        <!-- Basic Forms -->
        <div class="box">
            <div class="box-header with-border">
                <h4 class="box-title">Admin Profile Edit</h4>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col">
                        <form action="{{ route('admin.profile.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-12">

                                    <div class="row">
                                        <div class="col-md-6">

                                            <div class="form-group">
                                                <h5>Admin User Name<span class="text-danger">*</span></h5>
                                                <div class="controls">
                                                    <input type="text" name="name" class="form-control" required=""
                                                        value="{{ $adminData->name }}">
                                                    <div class="help-block"></div>
                                                </div>
                                            </div>

                                        </div>
                                        <div class="col-md-6">

                                            <div class="form-group">
                                                <h5>Admin Email<span class="text-danger">*</span></h5>
                                                <div class="controls">
                                                    <input type="email" name="email" class="form-control"
                                                        required="" value="{{ $adminData->email }}">
                                                    <div class="help-block"></div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">

                                            <div class="form-group">
                                                <h5>Profile Image <span class="text-danger">*</span></h5>
                                                <div class="controls">
                                                    <input type="file" id="image" name="profile_photo_path"
                                                        class="form-control" required="">
                                                    <div class="help-block"></div>
                                                </div>
                                            </div>


                                        </div>
                                        <div class="col-md-6">

                                            <img src="{{ $adminData->profile_image }}" id="showImage"
                                                style="width: 100px" height="100px">

                                        </div>
                                    </div>




                                    <div class="text-xs-right">
                                        <button type="submit" class="btn btn-rounded btn-primary">Update</button>
                                    </div>
                        </form>

                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->

    </section>
</div>
<script type="text/javascript">
    $(document).ready(function(){
            $('#image').change(function(e){
                var reader = new FileReader();
                reader.onload = function(e){
                    $('#showImage').attr('src',e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            });
        });
</script>
@endsection

resources/views/admin/admin_profile_view.blade.php
@extends('admin.admin_master')
@section('admin')
<div class="container-full">

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="box box-widget widget-user">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-black">
                    <h3 class="widget-user-username">Admin Name: {{ $adminData->name }}</h3>
                    <a href="{{ route('admin.profile_edit') }}" style="float: right"
                        class="btn btn-rounded btn-success mb-5">Edit Profile</a>
                    <h6 class="widget-user-desc">Admin Email: {{ $adminData->email }}</h6>
                </div>
                <div class="widget-user-image">
                    <img class="rounded-circle" src="{{ $adminData->profile_image }}" alt="User Avatar">
                </div>
                <div class="box-footer">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="description-block">
                                <h5 class="description-header">12K</h5>
                                <span class="description-text">FOLLOWERS</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 br-1 bl-1">
                            <div class="description-block">
                                <h5 class="description-header">550</h5>
                                <span class="description-text">FOLLOWERS</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4">
                            <div class="description-block">
                                <h5 class="description-header">158</h5>
                                <span class="description-text">TWEETS</span>
                            </div>
                            <!-- /.description-block -->
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
@endsection